/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_ascia_bentel_JBisKyoUnit */

#ifndef _Included_it_ascia_bentel_JBisKyoUnit
#define _Included_it_ascia_bentel_JBisKyoUnit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_ascia_bentel_JBisKyoUnit
 * Method:    PanelConnection
 * Signature: (IBBLjava/lang/String;[B)B
 */
JNIEXPORT jbyte JNICALL Java_it_ascia_bentel_JBisKyoUnit_PanelConnection
  (JNIEnv *, jclass, jint, jbyte, jbyte, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
