/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_ascia_bentel_JBisKyoUnit */

#ifndef _Included_it_ascia_bentel_JBisKyoUnit
#define _Included_it_ascia_bentel_JBisKyoUnit
#ifdef __cplusplus
extern "C" {
#endif
#undef it_ascia_bentel_JBisKyoUnit_LOG_SIZE
#define it_ascia_bentel_JBisKyoUnit_LOG_SIZE 128L
#undef it_ascia_bentel_JBisKyoUnit_MAX_LOG_SIZE
#define it_ascia_bentel_JBisKyoUnit_MAX_LOG_SIZE 100L
/*
 * Class:     it_ascia_bentel_JBisKyoUnit
 * Method:    openLibrary
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_it_ascia_bentel_JBisKyoUnit_openLibrary
  (JNIEnv *, jobject);

/*
 * Class:     it_ascia_bentel_JBisKyoUnit
 * Method:    PanelConnection
 * Signature: (IBBLjava/lang/String;[B)B
 */
JNIEXPORT jbyte JNICALL Java_it_ascia_bentel_JBisKyoUnit_PanelConnection
  (JNIEnv *, jclass, jint, jbyte, jbyte, jstring, jbyteArray);

/*
 * Class:     it_ascia_bentel_JBisKyoUnit
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_it_ascia_bentel_JBisKyoUnit_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
